(() => {
  "use strict";

  const SKIP_HOSTS = new Set([
    "gemini.google.com",
    "bard.google.com",
    "aistudio.google.com",
    "notebooklm.google.com",
    "labs.google.com",
    "ai.google.dev",
    "one.google.com",
  ]);

  const SEARCH_PHRASES = [
    "ai overview",
    "ai overviews",
    "generated by ai",
    "learn about ai overviews",
  ];

  const WORKSPACE_LABELS = [
    "ask gemini",
    "gemini",
    "open gemini",
    "try gemini",
    "help me write",
    "help me write with gemini",
    "summarize this email",
    "summarize this thread",
    "gemini side panel",
    "draft with gemini",
    "refine with gemini",
  ];

  const SEARCH_SELECTORS = [
    ".YzCcne",
    ".Beswgc",
    '[data-attrid="AIOverview"]',
    '[data-async-type="folsrch"]',
    '[aria-label="AI Mode"]',
    '[aria-label="AI Overview"]',
    'a[href*="udm=50"]',
    'a[href*="p=ai_overviews"]',
  ];

  const WORKSPACE_SELECTORS = [
    ".appsElementsSidekickEntryPointRoot",
    ".appsElementsSidekickAuroraEntryPointRoot",
    "#docs-sidekick-gen-ai-promo-button-container",
    "#docs-instant-bubble",
    ".kixWizBarkickWrapper",
    '[aria-label="Ask Gemini"]',
    '[aria-label="Gemini"]',
    '[aria-label*="Ask Gemini"]',
    '[data-tooltip="Ask Gemini"]',
    '[data-tooltip="Gemini"]',
    '[aria-label="Help me write"]',
    '[data-tooltip="Help me write"]',
    '[aria-label="Help me write with Gemini"]',
    '[aria-label="Summarize this email"]',
    '[aria-label="Open Gemini"]',
  ];

  const LS_ON = "__dslop_on";
  const LS_SEARCH = "__dslop_search";
  const LS_WS = "__dslop_ws";
  const LS_YT = "__dslop_yt";
  const ext = typeof browser !== "undefined" ? browser : chrome;

  let enabled = true;
  let hideSearch = true;
  let hideWorkspace = true;
  let hideYoutube = true;
  let observer = null;
  let sweepTimer = 0;

  try {
    if (localStorage.getItem(LS_ON) === "0") {
      enabled = false;
      document.documentElement.classList.add("dslop-off");
    }
    if (localStorage.getItem(LS_SEARCH) === "0") {
      hideSearch = false;
      document.documentElement.classList.add("dslop-search-off");
    }
    if (localStorage.getItem(LS_WS) === "0") {
      hideWorkspace = false;
      document.documentElement.classList.add("dslop-workspace-off");
    }
    if (localStorage.getItem(LS_YT) === "0") {
      hideYoutube = false;
      document.documentElement.classList.add("dslop-youtube-off");
    }
  } catch {
    /* ignore */
  }

  function host() {
    return location.hostname.replace(/^www\./, "");
  }

  function isSkipped() {
    const name = host();
    if (SKIP_HOSTS.has(name)) return true;
    return [...SKIP_HOSTS].some((item) => name === item || name.endsWith(`.${item}`));
  }

  function isSearchPage() {
    const name = host();
    if (name === "google.com" || name.startsWith("google.") || name.endsWith(".google.com")) {
      if (name.startsWith("mail.") || name.startsWith("docs.") || name.startsWith("drive.")) {
        return false;
      }
      if (name.startsWith("calendar.") || name.startsWith("meet.") || name.startsWith("chat.")) {
        return false;
      }
      return name === "google.com" || /^google\./.test(name) || name.startsWith("www.google.");
    }
    return false;
  }

  function isWorkspacePage() {
    const name = host();
    return (
      name.startsWith("mail.google.") ||
      name.startsWith("docs.google.") ||
      name.startsWith("drive.google.") ||
      name.startsWith("calendar.google.") ||
      name.startsWith("meet.google.") ||
      name.startsWith("chat.google.") ||
      name.startsWith("sheets.google.") ||
      name === "docs.google.com" ||
      name === "mail.google.com" ||
      name === "drive.google.com"
    );
  }

  function isYoutubePage() {
    return host() === "youtube.com" || host().endsWith(".youtube.com");
  }

  function storageGet(defaults) {
    return new Promise((resolve) => {
      try {
        if (typeof browser !== "undefined" && browser.storage) {
          browser.storage.local.get(defaults).then(resolve, () => resolve(defaults));
          return;
        }
        ext.storage.local.get(defaults, (result) => resolve(result || defaults));
      } catch {
        resolve(defaults);
      }
    });
  }

  function hideNode(node, cls) {
    if (!node || node.classList.contains(cls)) return;
    node.classList.add(cls);
  }

  function hideBySelectors(selectors, cls) {
    for (const selector of selectors) {
      let nodes;
      try {
        nodes = document.querySelectorAll(selector);
      } catch {
        continue;
      }
      for (const node of nodes) hideNode(node, cls);
    }
  }

  function labelOf(el) {
    return `${el.getAttribute("aria-label") || ""} ${el.getAttribute("data-tooltip") || ""} ${el.getAttribute("title") || ""} ${el.getAttribute("aria-description") || ""}`
      .trim()
      .toLowerCase();
  }

  function textOf(el) {
    return `${el.textContent || ""}`.trim().toLowerCase().replace(/\s+/g, " ");
  }

  function sweepSearch() {
    if (!hideSearch || !isSearchPage() || !document.body) return;
    hideBySelectors(SEARCH_SELECTORS, "dslop-hidden");

    document.querySelectorAll('[role="listitem"], a, button, [role="tab"]').forEach((el) => {
      const label = labelOf(el);
      const text = textOf(el);
      if (label === "ai mode" || text === "ai mode" || label.includes("ai overview")) {
        const hostEl = el.closest('[role="listitem"], [role="tab"], div') || el;
        hideNode(hostEl, "dslop-hidden");
      }
    });

    document.querySelectorAll("h1, h2, span[role='heading']").forEach((el) => {
      const text = textOf(el);
      if (!SEARCH_PHRASES.includes(text) && text !== "ai overview") return;
      let parent = el.parentElement;
      for (let i = 0; parent && i < 8; i += 1) {
        const rect = parent.getBoundingClientRect();
        if (rect.height > 80 && rect.width > 240) {
          hideNode(parent, "dslop-hidden");
          return;
        }
        parent = parent.parentElement;
      }
    });
  }

  function sweepWorkspace() {
    if (!hideWorkspace || !isWorkspacePage() || !document.body) return;
    hideBySelectors(WORKSPACE_SELECTORS, "dslop-ws-hidden");

    document.querySelectorAll("button, [role='button'], a, div[aria-label]").forEach((el) => {
      const label = labelOf(el);
      if (!label || label.length > 64) return;
      if (!WORKSPACE_LABELS.some((item) => label === item || label.startsWith(`${item} `))) {
        return;
      }
      hideNode(el, "dslop-ws-hidden");
    });
  }

  function sweepYoutube() {
    if (!hideYoutube || !isYoutubePage() || !document.body) return;
    document.querySelectorAll("button, [role='button'], ytd-button-renderer, yt-button-shape").forEach((el) => {
      const label = labelOf(el);
      const text = textOf(el);
      if (
        label.includes("gemini") ||
        label.includes("ai-generated") ||
        text.includes("ai-generated summary") ||
        text.includes("ask gemini")
      ) {
        hideNode(el, "dslop-yt-hidden");
      }
    });
  }

  function sweep() {
    if (!enabled || isSkipped() || !document.body) return;
    sweepSearch();
    sweepWorkspace();
    sweepYoutube();
  }

  function scheduleSweep() {
    if (sweepTimer) return;
    sweepTimer = window.setTimeout(() => {
      sweepTimer = 0;
      sweep();
    }, 50);
  }

  function startObserver() {
    if (observer || !document.documentElement) return;
    observer = new MutationObserver(scheduleSweep);
    observer.observe(document.documentElement, {
      childList: true,
      subtree: true,
      attributes: true,
      attributeFilter: ["aria-label", "data-tooltip", "class"],
    });
  }

  function applyFlags() {
    document.documentElement.classList.toggle("dslop-off", !enabled);
    document.documentElement.classList.toggle("dslop-search-off", !hideSearch);
    document.documentElement.classList.toggle("dslop-workspace-off", !hideWorkspace);
    document.documentElement.classList.toggle("dslop-youtube-off", !hideYoutube);
    try {
      localStorage.setItem(LS_ON, enabled ? "1" : "0");
      localStorage.setItem(LS_SEARCH, hideSearch ? "1" : "0");
      localStorage.setItem(LS_WS, hideWorkspace ? "1" : "0");
      localStorage.setItem(LS_YT, hideYoutube ? "1" : "0");
    } catch {
      /* ignore */
    }
  }

  function start() {
    if (isSkipped()) return;
    applyFlags();
    sweep();
    startObserver();
  }

  storageGet({
    enabled: true,
    hideSearch: true,
    hideWorkspace: true,
    hideYoutube: true,
  }).then((result) => {
    enabled = result.enabled !== false;
    hideSearch = result.hideSearch !== false;
    hideWorkspace = result.hideWorkspace !== false;
    hideYoutube = result.hideYoutube !== false;
    if (enabled) start();
    else applyFlags();
  });

  try {
    ext.storage.onChanged.addListener((changes, area) => {
      if (area !== "local") return;
      if (changes.enabled) enabled = changes.enabled.newValue !== false;
      if (changes.hideSearch) hideSearch = changes.hideSearch.newValue !== false;
      if (changes.hideWorkspace) hideWorkspace = changes.hideWorkspace.newValue !== false;
      if (changes.hideYoutube) hideYoutube = changes.hideYoutube.newValue !== false;
      applyFlags();
      if (enabled) {
        startObserver();
        sweep();
      }
    });
  } catch {
    /* ignore */
  }
})();
